#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : nodejs
Version  : 8.14.0
Release  : 68
URL      : https://nodejs.org/dist/v8.14.0/node-v8.14.0.tar.gz
Source0  : https://nodejs.org/dist/v8.14.0/node-v8.14.0.tar.gz
Summary  : Node.js is a platform for building fast, scalable network applications.
Group    : Development/Tools
License  : Apache-2.0 Artistic-2.0 BSD-2-Clause BSD-2-Clause-FreeBSD BSD-2-Clause-NetBSD BSD-3-Clause BSD-4-Clause CC-BY-4.0 HPND ICU ISC MIT OpenSSL Unlicense Zlib bzip2-1.0.6
Requires: nodejs-license = %{version}-%{release}
Requires: MarkupSafe-python3
BuildRequires : MarkupSafe-python3
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : openssl-dev
BuildRequires : python-core
BuildRequires : util-linux
BuildRequires : zlib-dev
Patch1: 0001-Let-nodejs-configure-file-recipe-uknown-options.patch

%description
Node.js is a platform built on Chrome's JavaScript runtime for easily
building fast, scalable network applications.

Node.js uses an event-driven, non-blocking I/O model that makes it
lightweight and efficient, perfect for data-intensive real-time
applications that run across distributed devices.

%package license
Summary: license components for the nodejs package.
Group: Default

%description license
license components for the nodejs package.


%prep
%setup -q -n node-v8.14.0
%patch1 -p1

%build
## build_prepend content
./configure  --shared-zlib --shared-openssl
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1543438401
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1543438401
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/nodejs
cp LICENSE %{buildroot}/usr/share/package-licenses/nodejs/LICENSE
cp deps/gtest/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_gtest_LICENSE
cp deps/http_parser/LICENSE-MIT %{buildroot}/usr/share/package-licenses/nodejs/deps_http_parser_LICENSE-MIT
cp deps/icu-small/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_icu-small_LICENSE
cp deps/nghttp2/COPYING %{buildroot}/usr/share/package-licenses/nodejs/deps_nghttp2_COPYING
cp deps/node-inspect/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_node-inspect_LICENSE
cp deps/npm/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_LICENSE
cp deps/npm/node_modules/JSONStream/LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_JSONStream_LICENSE.APACHE2
cp deps/npm/node_modules/JSONStream/LICENSE.MIT %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_JSONStream_LICENSE.MIT
cp deps/npm/node_modules/abbrev/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_abbrev_LICENSE
cp deps/npm/node_modules/ajv/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ajv_LICENSE
cp deps/npm/node_modules/ansi-align/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-align_LICENSE
cp deps/npm/node_modules/ansi-regex/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-regex_license
cp deps/npm/node_modules/ansi-styles/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-styles_license
cp deps/npm/node_modules/ansicolors/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansicolors_LICENSE
cp deps/npm/node_modules/ansistyles/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansistyles_LICENSE
cp deps/npm/node_modules/aproba/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_aproba_LICENSE
cp deps/npm/node_modules/archy/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_archy_LICENSE
cp deps/npm/node_modules/are-we-there-yet/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_are-we-there-yet_LICENSE
cp deps/npm/node_modules/asap/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_asap_LICENSE.md
cp deps/npm/node_modules/asn1/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_asn1_LICENSE
cp deps/npm/node_modules/asynckit/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_asynckit_LICENSE
cp deps/npm/node_modules/aws-sign2/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_aws-sign2_LICENSE
cp deps/npm/node_modules/aws4/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_aws4_LICENSE
cp deps/npm/node_modules/balanced-match/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_balanced-match_LICENSE.md
cp deps/npm/node_modules/bcrypt-pbkdf/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_bcrypt-pbkdf_LICENSE
cp deps/npm/node_modules/bin-links/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_bin-links_LICENSE
cp deps/npm/node_modules/block-stream/LICENCE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_block-stream_LICENCE
cp deps/npm/node_modules/block-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_block-stream_LICENSE
cp deps/npm/node_modules/bluebird/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_bluebird_LICENSE
cp deps/npm/node_modules/boxen/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_boxen_license
cp deps/npm/node_modules/brace-expansion/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_brace-expansion_LICENSE
cp deps/npm/node_modules/builtin-modules/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_builtin-modules_license
cp deps/npm/node_modules/builtins/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_builtins_License
cp deps/npm/node_modules/byline/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_byline_LICENSE
cp deps/npm/node_modules/byte-size/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_byte-size_LICENSE
cp deps/npm/node_modules/cacache/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cacache_LICENSE.md
cp deps/npm/node_modules/camelcase/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_camelcase_license
cp deps/npm/node_modules/caseless/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_caseless_LICENSE
cp deps/npm/node_modules/chalk/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_chalk_license
cp deps/npm/node_modules/chownr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_chownr_LICENSE
cp deps/npm/node_modules/ci-info/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ci-info_LICENSE
cp deps/npm/node_modules/cidr-regex/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cidr-regex_LICENSE
cp deps/npm/node_modules/cli-boxes/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-boxes_license
cp deps/npm/node_modules/cli-columns/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-columns_LICENSE
cp deps/npm/node_modules/cli-table3/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-table3_LICENSE
cp deps/npm/node_modules/cliui/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_LICENSE.txt
cp deps/npm/node_modules/cliui/node_modules/ansi-regex/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_node_modules_ansi-regex_license
cp deps/npm/node_modules/cliui/node_modules/strip-ansi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_node_modules_strip-ansi_license
cp deps/npm/node_modules/clone/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_clone_LICENSE
cp deps/npm/node_modules/cmd-shim/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cmd-shim_LICENSE
cp deps/npm/node_modules/co/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_co_LICENSE
cp deps/npm/node_modules/code-point-at/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_code-point-at_license
cp deps/npm/node_modules/color-convert/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_color-convert_LICENSE
cp deps/npm/node_modules/color-name/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_color-name_LICENSE
cp deps/npm/node_modules/colors/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_colors_LICENSE
cp deps/npm/node_modules/columnify/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_columnify_LICENSE
cp deps/npm/node_modules/combined-stream/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_combined-stream_License
cp deps/npm/node_modules/concat-map/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_concat-map_LICENSE
cp deps/npm/node_modules/concat-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_concat-stream_LICENSE
cp deps/npm/node_modules/config-chain/LICENCE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_config-chain_LICENCE
cp deps/npm/node_modules/configstore/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_configstore_license
cp deps/npm/node_modules/console-control-strings/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_console-control-strings_LICENSE
cp deps/npm/node_modules/copy-concurrently/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_copy-concurrently_LICENSE
cp deps/npm/node_modules/copy-concurrently/node_modules/iferr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_copy-concurrently_node_modules_iferr_LICENSE
cp deps/npm/node_modules/core-util-is/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_core-util-is_LICENSE
cp deps/npm/node_modules/create-error-class/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_create-error-class_license
cp deps/npm/node_modules/cross-spawn/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_cross-spawn_LICENSE
cp deps/npm/node_modules/crypto-random-string/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_crypto-random-string_license
cp deps/npm/node_modules/dashdash/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_dashdash_LICENSE.txt
cp deps/npm/node_modules/debug/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_debug_LICENSE
cp deps/npm/node_modules/debug/node_modules/ms/license.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_debug_node_modules_ms_license.md
cp deps/npm/node_modules/debuglog/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_debuglog_LICENSE
cp deps/npm/node_modules/decamelize/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_decamelize_license
cp deps/npm/node_modules/decode-uri-component/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_decode-uri-component_license
cp deps/npm/node_modules/deep-extend/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_deep-extend_LICENSE
cp deps/npm/node_modules/defaults/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_defaults_LICENSE
cp deps/npm/node_modules/delayed-stream/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_delayed-stream_License
cp deps/npm/node_modules/delegates/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_delegates_License
cp deps/npm/node_modules/detect-indent/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_detect-indent_license
cp deps/npm/node_modules/detect-newline/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_detect-newline_license
cp deps/npm/node_modules/dezalgo/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_dezalgo_LICENSE
cp deps/npm/node_modules/dot-prop/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_dot-prop_license
cp deps/npm/node_modules/dotenv/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_dotenv_LICENSE
cp deps/npm/node_modules/duplexer3/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_duplexer3_LICENSE.md
cp deps/npm/node_modules/duplexify/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_duplexify_LICENSE
cp deps/npm/node_modules/ecc-jsbn/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ecc-jsbn_LICENSE
cp deps/npm/node_modules/ecc-jsbn/lib/LICENSE-jsbn %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ecc-jsbn_lib_LICENSE-jsbn
cp deps/npm/node_modules/editor/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_editor_LICENSE
cp deps/npm/node_modules/encoding/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_encoding_LICENSE
cp deps/npm/node_modules/end-of-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_end-of-stream_LICENSE
cp deps/npm/node_modules/es6-promise/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_es6-promise_LICENSE
cp deps/npm/node_modules/escape-string-regexp/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_escape-string-regexp_license
cp deps/npm/node_modules/execa/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_execa_license
cp deps/npm/node_modules/extend/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_extend_LICENSE
cp deps/npm/node_modules/extsprintf/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_extsprintf_LICENSE
cp deps/npm/node_modules/fast-deep-equal/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fast-deep-equal_LICENSE
cp deps/npm/node_modules/fast-json-stable-stringify/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fast-json-stable-stringify_LICENSE
cp deps/npm/node_modules/figgy-pudding/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_figgy-pudding_LICENSE.md
cp deps/npm/node_modules/find-npm-prefix/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_find-npm-prefix_LICENSE
cp deps/npm/node_modules/find-up/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_find-up_license
cp deps/npm/node_modules/flush-write-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_flush-write-stream_LICENSE
cp deps/npm/node_modules/forever-agent/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_forever-agent_LICENSE
cp deps/npm/node_modules/form-data/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_form-data_License
cp deps/npm/node_modules/from2/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_from2_LICENSE.md
cp deps/npm/node_modules/fs-minipass/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-minipass_LICENSE
cp deps/npm/node_modules/fs-vacuum/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-vacuum_LICENSE
cp deps/npm/node_modules/fs-write-stream-atomic/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-write-stream-atomic_LICENSE
cp deps/npm/node_modules/fs-write-stream-atomic/node_modules/iferr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-write-stream-atomic_node_modules_iferr_LICENSE
cp deps/npm/node_modules/fs.realpath/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs.realpath_LICENSE
cp deps/npm/node_modules/fstream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_fstream_LICENSE
cp deps/npm/node_modules/gauge/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_gauge_LICENSE
cp deps/npm/node_modules/gauge/node_modules/string-width/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_gauge_node_modules_string-width_license
cp deps/npm/node_modules/gentle-fs/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_gentle-fs_LICENSE
cp deps/npm/node_modules/gentle-fs/node_modules/iferr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_gentle-fs_node_modules_iferr_LICENSE
cp deps/npm/node_modules/get-stream/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_get-stream_license
cp deps/npm/node_modules/getpass/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_getpass_LICENSE
cp deps/npm/node_modules/glob/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_glob_LICENSE
cp deps/npm/node_modules/global-dirs/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_global-dirs_license
cp deps/npm/node_modules/got/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_got_license
cp deps/npm/node_modules/graceful-fs/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_graceful-fs_LICENSE
cp deps/npm/node_modules/har-schema/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_har-schema_LICENSE
cp deps/npm/node_modules/har-validator/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_har-validator_LICENSE
cp deps/npm/node_modules/has-flag/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_has-flag_license
cp deps/npm/node_modules/has-unicode/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_has-unicode_LICENSE
cp deps/npm/node_modules/hosted-git-info/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_hosted-git-info_LICENSE
cp deps/npm/node_modules/http-signature/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_http-signature_LICENSE
cp deps/npm/node_modules/humanize-ms/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_humanize-ms_LICENSE
cp deps/npm/node_modules/iconv-lite/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_iconv-lite_LICENSE
cp deps/npm/node_modules/iferr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_iferr_LICENSE
cp deps/npm/node_modules/ignore-walk/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ignore-walk_LICENSE
cp deps/npm/node_modules/import-lazy/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_import-lazy_license
cp deps/npm/node_modules/inflight/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_inflight_LICENSE
cp deps/npm/node_modules/inherits/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_inherits_LICENSE
cp deps/npm/node_modules/ini/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ini_LICENSE
cp deps/npm/node_modules/init-package-json/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_init-package-json_LICENSE
cp deps/npm/node_modules/ip-regex/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ip-regex_license
cp deps/npm/node_modules/is-builtin-module/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-builtin-module_license
cp deps/npm/node_modules/is-ci/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-ci_LICENSE
cp deps/npm/node_modules/is-cidr/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-cidr_LICENSE
cp deps/npm/node_modules/is-fullwidth-code-point/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-fullwidth-code-point_license
cp deps/npm/node_modules/is-installed-globally/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-installed-globally_license
cp deps/npm/node_modules/is-obj/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-obj_license
cp deps/npm/node_modules/is-path-inside/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-path-inside_license
cp deps/npm/node_modules/is-redirect/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-redirect_license
cp deps/npm/node_modules/is-retry-allowed/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-retry-allowed_license
cp deps/npm/node_modules/is-stream/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-stream_license
cp deps/npm/node_modules/is-typedarray/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-typedarray_LICENSE.md
cp deps/npm/node_modules/isexe/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_isexe_LICENSE
cp deps/npm/node_modules/isstream/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_isstream_LICENSE.md
cp deps/npm/node_modules/jsbn/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsbn_LICENSE
cp deps/npm/node_modules/json-parse-better-errors/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-parse-better-errors_LICENSE.md
cp deps/npm/node_modules/json-schema-traverse/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-schema-traverse_LICENSE
cp deps/npm/node_modules/json-stringify-safe/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-stringify-safe_LICENSE
cp deps/npm/node_modules/jsonparse/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsonparse_LICENSE
cp deps/npm/node_modules/jsprim/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsprim_LICENSE
cp deps/npm/node_modules/latest-version/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_latest-version_license
cp deps/npm/node_modules/lazy-property/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lazy-property_LICENSE
cp deps/npm/node_modules/lcid/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lcid_license
cp deps/npm/node_modules/libcipm/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_libcipm_LICENSE.md
cp deps/npm/node_modules/libnpmhook/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpmhook_LICENSE.md
cp deps/npm/node_modules/libnpmhook/node_modules/npm-registry-fetch/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpmhook_node_modules_npm-registry-fetch_LICENSE.md
cp deps/npm/node_modules/libnpx/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpx_LICENSE.md
cp deps/npm/node_modules/locate-path/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_locate-path_license
cp deps/npm/node_modules/lock-verify/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lock-verify_LICENSE
cp deps/npm/node_modules/lockfile/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lockfile_LICENSE
cp deps/npm/node_modules/lodash._baseindexof/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._baseindexof_LICENSE.txt
cp deps/npm/node_modules/lodash._baseuniq/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._baseuniq_LICENSE
cp deps/npm/node_modules/lodash._bindcallback/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._bindcallback_LICENSE.txt
cp deps/npm/node_modules/lodash._cacheindexof/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._cacheindexof_LICENSE.txt
cp deps/npm/node_modules/lodash._createcache/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._createcache_LICENSE
cp deps/npm/node_modules/lodash._createset/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._createset_LICENSE
cp deps/npm/node_modules/lodash._getnative/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._getnative_LICENSE
cp deps/npm/node_modules/lodash._root/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._root_LICENSE
cp deps/npm/node_modules/lodash.clonedeep/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.clonedeep_LICENSE
cp deps/npm/node_modules/lodash.restparam/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.restparam_LICENSE.txt
cp deps/npm/node_modules/lodash.union/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.union_LICENSE
cp deps/npm/node_modules/lodash.uniq/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.uniq_LICENSE
cp deps/npm/node_modules/lodash.without/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.without_LICENSE
cp deps/npm/node_modules/lowercase-keys/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lowercase-keys_license
cp deps/npm/node_modules/lru-cache/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_lru-cache_LICENSE
cp deps/npm/node_modules/make-dir/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_make-dir_license
cp deps/npm/node_modules/make-fetch-happen/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_make-fetch-happen_LICENSE
cp deps/npm/node_modules/meant/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_meant_LICENSE
cp deps/npm/node_modules/mem/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mem_license
cp deps/npm/node_modules/mime-db/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mime-db_LICENSE
cp deps/npm/node_modules/mime-types/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mime-types_LICENSE
cp deps/npm/node_modules/mimic-fn/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mimic-fn_license
cp deps/npm/node_modules/minimatch/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_minimatch_LICENSE
cp deps/npm/node_modules/minimist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_minimist_LICENSE
cp deps/npm/node_modules/minipass/node_modules/yallist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_minipass_node_modules_yallist_LICENSE
cp deps/npm/node_modules/minizlib/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_minizlib_LICENSE
cp deps/npm/node_modules/mississippi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mississippi_license
cp deps/npm/node_modules/mkdirp/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mkdirp_LICENSE
cp deps/npm/node_modules/move-concurrently/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_move-concurrently_LICENSE
cp deps/npm/node_modules/ms/license.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ms_license.md
cp deps/npm/node_modules/mute-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_mute-stream_LICENSE
cp deps/npm/node_modules/node-fetch-npm/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-fetch-npm_LICENSE.md
cp deps/npm/node_modules/node-gyp/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_LICENSE
cp deps/npm/node_modules/node-gyp/gyp/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_gyp_LICENSE
cp deps/npm/node_modules/node-gyp/node_modules/nopt/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_nopt_LICENSE
cp deps/npm/node_modules/node-gyp/node_modules/semver/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_semver_LICENSE
cp deps/npm/node_modules/node-gyp/node_modules/tar/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_tar_LICENSE
cp deps/npm/node_modules/nopt/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_nopt_LICENSE
cp deps/npm/node_modules/normalize-package-data/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_normalize-package-data_LICENSE
cp deps/npm/node_modules/npm-audit-report/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-audit-report_LICENSE
cp deps/npm/node_modules/npm-bundled/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-bundled_LICENSE
cp deps/npm/node_modules/npm-cache-filename/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-cache-filename_LICENSE
cp deps/npm/node_modules/npm-install-checks/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-install-checks_LICENSE
cp deps/npm/node_modules/npm-lifecycle/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-lifecycle_LICENSE
cp deps/npm/node_modules/npm-logical-tree/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-logical-tree_LICENSE.md
cp deps/npm/node_modules/npm-package-arg/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-package-arg_LICENSE
cp deps/npm/node_modules/npm-packlist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-packlist_LICENSE
cp deps/npm/node_modules/npm-pick-manifest/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-pick-manifest_LICENSE.md
cp deps/npm/node_modules/npm-profile/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-profile_LICENSE
cp deps/npm/node_modules/npm-registry-client/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_LICENSE
cp deps/npm/node_modules/npm-registry-client/node_modules/retry/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_node_modules_retry_License
cp deps/npm/node_modules/npm-registry-client/node_modules/ssri/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_node_modules_ssri_LICENSE.md
cp deps/npm/node_modules/npm-registry-fetch/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_LICENSE.md
cp deps/npm/node_modules/npm-registry-fetch/node_modules/cacache/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_cacache_LICENSE.md
cp deps/npm/node_modules/npm-registry-fetch/node_modules/cacache/node_modules/mississippi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_cacache_node_modules_mississippi_license
cp deps/npm/node_modules/npm-registry-fetch/node_modules/figgy-pudding/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_figgy-pudding_LICENSE.md
cp deps/npm/node_modules/npm-registry-fetch/node_modules/make-fetch-happen/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_make-fetch-happen_LICENSE
cp deps/npm/node_modules/npm-registry-fetch/node_modules/pump/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_pump_LICENSE
cp deps/npm/node_modules/npm-registry-fetch/node_modules/smart-buffer/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_smart-buffer_LICENSE
cp deps/npm/node_modules/npm-registry-fetch/node_modules/socks/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_socks_LICENSE
cp deps/npm/node_modules/npm-registry-fetch/node_modules/ssri/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_ssri_LICENSE.md
cp deps/npm/node_modules/npm-run-path/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-run-path_license
cp deps/npm/node_modules/npm-user-validate/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-user-validate_LICENSE
cp deps/npm/node_modules/npmlog/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_npmlog_LICENSE
cp deps/npm/node_modules/number-is-nan/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_number-is-nan_license
cp deps/npm/node_modules/oauth-sign/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_oauth-sign_LICENSE
cp deps/npm/node_modules/object-assign/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_object-assign_license
cp deps/npm/node_modules/once/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_once_LICENSE
cp deps/npm/node_modules/opener/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_opener_LICENSE.txt
cp deps/npm/node_modules/os-homedir/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-homedir_license
cp deps/npm/node_modules/os-locale/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-locale_license
cp deps/npm/node_modules/os-tmpdir/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-tmpdir_license
cp deps/npm/node_modules/osenv/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_osenv_LICENSE
cp deps/npm/node_modules/p-finally/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-finally_license
cp deps/npm/node_modules/p-limit/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-limit_license
cp deps/npm/node_modules/p-locate/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-locate_license
cp deps/npm/node_modules/p-try/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-try_license
cp deps/npm/node_modules/package-json/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_package-json_license
cp deps/npm/node_modules/pacote/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pacote_LICENSE
cp deps/npm/node_modules/parallel-transform/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_parallel-transform_LICENSE
cp deps/npm/node_modules/path-exists/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-exists_license
cp deps/npm/node_modules/path-is-absolute/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-is-absolute_license
cp deps/npm/node_modules/path-is-inside/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-is-inside_LICENSE.txt
cp deps/npm/node_modules/path-key/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-key_license
cp deps/npm/node_modules/performance-now/license.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_performance-now_license.txt
cp deps/npm/node_modules/pify/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pify_license
cp deps/npm/node_modules/prepend-http/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_prepend-http_license
cp deps/npm/node_modules/process-nextick-args/license.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_process-nextick-args_license.md
cp deps/npm/node_modules/promise-inflight/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-inflight_LICENSE
cp deps/npm/node_modules/promise-retry/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-retry_LICENSE
cp deps/npm/node_modules/promise-retry/node_modules/retry/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-retry_node_modules_retry_License
cp deps/npm/node_modules/promzard/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_promzard_LICENSE
cp deps/npm/node_modules/proto-list/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_proto-list_LICENSE
cp deps/npm/node_modules/protoduck/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_protoduck_LICENSE
cp deps/npm/node_modules/prr/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_prr_LICENSE.md
cp deps/npm/node_modules/pseudomap/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pseudomap_LICENSE
cp deps/npm/node_modules/pump/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pump_LICENSE
cp deps/npm/node_modules/pumpify/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pumpify_LICENSE
cp deps/npm/node_modules/pumpify/node_modules/pump/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_pumpify_node_modules_pump_LICENSE
cp deps/npm/node_modules/punycode/LICENSE-MIT.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_punycode_LICENSE-MIT.txt
cp deps/npm/node_modules/qrcode-terminal/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_qrcode-terminal_LICENSE
cp deps/npm/node_modules/qs/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_qs_LICENSE
cp deps/npm/node_modules/query-string/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_query-string_license
cp deps/npm/node_modules/qw/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_qw_LICENSE
cp deps/npm/node_modules/rc/LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.APACHE2
cp deps/npm/node_modules/rc/LICENSE.BSD %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.BSD
cp deps/npm/node_modules/rc/LICENSE.MIT %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.MIT
cp deps/npm/node_modules/rc/node_modules/minimist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_node_modules_minimist_LICENSE
cp deps/npm/node_modules/read-installed/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-installed_LICENSE
cp deps/npm/node_modules/read-package-json/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-package-json_LICENSE
cp deps/npm/node_modules/read-package-tree/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-package-tree_LICENSE
cp deps/npm/node_modules/read/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_read_LICENSE
cp deps/npm/node_modules/readable-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_readable-stream_LICENSE
cp deps/npm/node_modules/readdir-scoped-modules/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_readdir-scoped-modules_LICENSE
cp deps/npm/node_modules/registry-auth-token/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_registry-auth-token_LICENSE
cp deps/npm/node_modules/registry-url/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_registry-url_license
cp deps/npm/node_modules/request/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_request_LICENSE
cp deps/npm/node_modules/require-directory/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_require-directory_LICENSE
cp deps/npm/node_modules/require-main-filename/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_require-main-filename_LICENSE.txt
cp deps/npm/node_modules/resolve-from/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_resolve-from_license
cp deps/npm/node_modules/retry/License %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_retry_License
cp deps/npm/node_modules/rimraf/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_rimraf_LICENSE
cp deps/npm/node_modules/safe-buffer/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_safe-buffer_LICENSE
cp deps/npm/node_modules/safer-buffer/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_safer-buffer_LICENSE
cp deps/npm/node_modules/semver-diff/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_semver-diff_license
cp deps/npm/node_modules/semver/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_semver_LICENSE
cp deps/npm/node_modules/set-blocking/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_set-blocking_LICENSE.txt
cp deps/npm/node_modules/sha/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sha_LICENSE
cp deps/npm/node_modules/shebang-command/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_shebang-command_license
cp deps/npm/node_modules/shebang-regex/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_shebang-regex_license
cp deps/npm/node_modules/signal-exit/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_signal-exit_LICENSE.txt
cp deps/npm/node_modules/slide/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_slide_LICENSE
cp deps/npm/node_modules/smart-buffer/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_smart-buffer_LICENSE
cp deps/npm/node_modules/socks/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_socks_LICENSE
cp deps/npm/node_modules/sorted-object/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-object_LICENSE.txt
cp deps/npm/node_modules/sorted-union-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_LICENSE
cp deps/npm/node_modules/sorted-union-stream/node_modules/from2/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_from2_LICENSE.md
cp deps/npm/node_modules/sorted-union-stream/node_modules/readable-stream/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_readable-stream_LICENSE
cp deps/npm/node_modules/sorted-union-stream/node_modules/string_decoder/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_string_decoder_LICENSE
cp deps/npm/node_modules/spdx-correct/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_spdx-correct_LICENSE
cp deps/npm/node_modules/spdx-expression-parse/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_spdx-expression-parse_LICENSE
cp deps/npm/node_modules/sshpk/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_sshpk_LICENSE
cp deps/npm/node_modules/ssri/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_ssri_LICENSE.md
cp deps/npm/node_modules/stream-each/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-each_LICENSE
cp deps/npm/node_modules/stream-iterate/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-iterate_LICENSE
cp deps/npm/node_modules/stream-shift/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-shift_LICENSE
cp deps/npm/node_modules/strict-uri-encode/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_strict-uri-encode_license
cp deps/npm/node_modules/string-width/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_license
cp deps/npm/node_modules/string-width/node_modules/ansi-regex/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_ansi-regex_license
cp deps/npm/node_modules/string-width/node_modules/is-fullwidth-code-point/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_is-fullwidth-code-point_license
cp deps/npm/node_modules/string-width/node_modules/strip-ansi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_strip-ansi_license
cp deps/npm/node_modules/string_decoder/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_string_decoder_LICENSE
cp deps/npm/node_modules/strip-ansi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-ansi_license
cp deps/npm/node_modules/strip-eof/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-eof_license
cp deps/npm/node_modules/strip-json-comments/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-json-comments_license
cp deps/npm/node_modules/supports-color/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_supports-color_license
cp deps/npm/node_modules/tar/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tar_LICENSE
cp deps/npm/node_modules/tar/node_modules/yallist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tar_node_modules_yallist_LICENSE
cp deps/npm/node_modules/term-size/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_term-size_license
cp deps/npm/node_modules/text-table/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_text-table_LICENSE
cp deps/npm/node_modules/through/LICENSE.APACHE2 %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_through_LICENSE.APACHE2
cp deps/npm/node_modules/through/LICENSE.MIT %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_through_LICENSE.MIT
cp deps/npm/node_modules/through2/LICENSE.html %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_through2_LICENSE.html
cp deps/npm/node_modules/through2/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_through2_LICENSE.md
cp deps/npm/node_modules/timed-out/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_timed-out_license
cp deps/npm/node_modules/tiny-relative-date/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tiny-relative-date_LICENSE.md
cp deps/npm/node_modules/tough-cookie/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tough-cookie_LICENSE
cp deps/npm/node_modules/tunnel-agent/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tunnel-agent_LICENSE
cp deps/npm/node_modules/tweetnacl/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_tweetnacl_LICENSE
cp deps/npm/node_modules/typedarray/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_typedarray_LICENSE
cp deps/npm/node_modules/uid-number/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_uid-number_LICENSE
cp deps/npm/node_modules/umask/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_umask_LICENSE
cp deps/npm/node_modules/unique-string/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_unique-string_license
cp deps/npm/node_modules/unpipe/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_unpipe_LICENSE
cp deps/npm/node_modules/unzip-response/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_unzip-response_license
cp deps/npm/node_modules/update-notifier/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_update-notifier_license
cp deps/npm/node_modules/url-parse-lax/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_url-parse-lax_license
cp deps/npm/node_modules/util-deprecate/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_util-deprecate_LICENSE
cp deps/npm/node_modules/util-extend/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_util-extend_LICENSE
cp deps/npm/node_modules/uuid/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_uuid_LICENSE.md
cp deps/npm/node_modules/validate-npm-package-license/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_validate-npm-package-license_LICENSE
cp deps/npm/node_modules/validate-npm-package-name/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_validate-npm-package-name_LICENSE
cp deps/npm/node_modules/verror/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_verror_LICENSE
cp deps/npm/node_modules/wcwidth/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wcwidth_LICENSE
cp deps/npm/node_modules/which-module/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_which-module_LICENSE
cp deps/npm/node_modules/which/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_which_LICENSE
cp deps/npm/node_modules/wide-align/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wide-align_LICENSE
cp deps/npm/node_modules/wide-align/node_modules/string-width/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wide-align_node_modules_string-width_license
cp deps/npm/node_modules/widest-line/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_widest-line_license
cp deps/npm/node_modules/worker-farm/LICENSE.md %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_worker-farm_LICENSE.md
cp deps/npm/node_modules/wrap-ansi/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrap-ansi_license
cp deps/npm/node_modules/wrap-ansi/node_modules/string-width/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrap-ansi_node_modules_string-width_license
cp deps/npm/node_modules/wrappy/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrappy_LICENSE
cp deps/npm/node_modules/write-file-atomic/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_write-file-atomic_LICENSE
cp deps/npm/node_modules/xdg-basedir/license %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_xdg-basedir_license
cp deps/npm/node_modules/xtend/LICENCE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_xtend_LICENCE
cp deps/npm/node_modules/y18n/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_y18n_LICENSE
cp deps/npm/node_modules/yallist/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_yallist_LICENSE
cp deps/npm/node_modules/yargs-parser/LICENSE.txt %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs-parser_LICENSE.txt
cp deps/npm/node_modules/yargs/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs_LICENSE
cp deps/npm/node_modules/yargs/node_modules/y18n/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs_node_modules_y18n_LICENSE
cp deps/openssl/openssl/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_openssl_openssl_LICENSE
cp deps/openssl/openssl/crypto/bf/COPYRIGHT %{buildroot}/usr/share/package-licenses/nodejs/deps_openssl_openssl_crypto_bf_COPYRIGHT
cp deps/openssl/openssl/crypto/des/COPYRIGHT %{buildroot}/usr/share/package-licenses/nodejs/deps_openssl_openssl_crypto_des_COPYRIGHT
cp deps/uv/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_uv_LICENSE
cp deps/uv/LICENSE-docs %{buildroot}/usr/share/package-licenses/nodejs/deps_uv_LICENSE-docs
cp deps/v8/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_LICENSE
cp deps/v8/LICENSE.fdlibm %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_LICENSE.fdlibm
cp deps/v8/LICENSE.strongtalk %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_LICENSE.strongtalk
cp deps/v8/LICENSE.v8 %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_LICENSE.v8
cp deps/v8/LICENSE.valgrind %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_LICENSE.valgrind
cp deps/v8/src/third_party/valgrind/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_src_third_party_valgrind_LICENSE
cp deps/v8/src/third_party/vtune/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_src_third_party_vtune_LICENSE
cp deps/v8/third_party/inspector_protocol/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_third_party_inspector_protocol_LICENSE
cp deps/v8/third_party/jinja2/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_third_party_jinja2_LICENSE
cp deps/v8/third_party/markupsafe/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/deps_v8_third_party_markupsafe_LICENSE
cp tools/doc/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/tools_doc_LICENSE
cp tools/doc/node_modules/marked/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/tools_doc_node_modules_marked_LICENSE
cp tools/gyp/LICENSE %{buildroot}/usr/share/package-licenses/nodejs/tools_gyp_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/nodejs/LICENSE
/usr/share/package-licenses/nodejs/deps_gtest_LICENSE
/usr/share/package-licenses/nodejs/deps_http_parser_LICENSE-MIT
/usr/share/package-licenses/nodejs/deps_icu-small_LICENSE
/usr/share/package-licenses/nodejs/deps_nghttp2_COPYING
/usr/share/package-licenses/nodejs/deps_node-inspect_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_JSONStream_LICENSE.APACHE2
/usr/share/package-licenses/nodejs/deps_npm_node_modules_JSONStream_LICENSE.MIT
/usr/share/package-licenses/nodejs/deps_npm_node_modules_abbrev_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ajv_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-align_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-regex_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansi-styles_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansicolors_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ansistyles_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_aproba_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_archy_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_are-we-there-yet_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_asap_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_asn1_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_asynckit_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_aws-sign2_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_aws4_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_balanced-match_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_bcrypt-pbkdf_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_bin-links_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_block-stream_LICENCE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_block-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_bluebird_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_boxen_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_brace-expansion_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_builtin-modules_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_builtins_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_byline_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_byte-size_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cacache_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_camelcase_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_caseless_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_chalk_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_chownr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ci-info_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cidr-regex_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-boxes_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-columns_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cli-table3_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_node_modules_ansi-regex_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cliui_node_modules_strip-ansi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_clone_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cmd-shim_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_co_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_code-point-at_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_color-convert_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_color-name_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_colors_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_columnify_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_combined-stream_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_concat-map_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_concat-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_config-chain_LICENCE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_configstore_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_console-control-strings_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_copy-concurrently_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_copy-concurrently_node_modules_iferr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_core-util-is_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_create-error-class_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_cross-spawn_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_crypto-random-string_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_dashdash_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_debug_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_debug_node_modules_ms_license.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_debuglog_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_decamelize_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_decode-uri-component_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_deep-extend_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_defaults_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_delayed-stream_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_delegates_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_detect-indent_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_detect-newline_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_dezalgo_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_dot-prop_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_dotenv_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_duplexer3_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_duplexify_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ecc-jsbn_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ecc-jsbn_lib_LICENSE-jsbn
/usr/share/package-licenses/nodejs/deps_npm_node_modules_editor_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_encoding_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_end-of-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_es6-promise_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_escape-string-regexp_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_execa_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_extend_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_extsprintf_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fast-deep-equal_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fast-json-stable-stringify_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_figgy-pudding_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_find-npm-prefix_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_find-up_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_flush-write-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_forever-agent_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_form-data_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_from2_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-minipass_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-vacuum_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-write-stream-atomic_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs-write-stream-atomic_node_modules_iferr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fs.realpath_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_fstream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_gauge_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_gauge_node_modules_string-width_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_gentle-fs_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_gentle-fs_node_modules_iferr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_get-stream_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_getpass_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_glob_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_global-dirs_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_got_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_graceful-fs_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_har-schema_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_har-validator_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_has-flag_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_has-unicode_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_hosted-git-info_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_http-signature_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_humanize-ms_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_iconv-lite_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_iferr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ignore-walk_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_import-lazy_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_inflight_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_inherits_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ini_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_init-package-json_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ip-regex_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-builtin-module_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-ci_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-cidr_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-fullwidth-code-point_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-installed-globally_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-obj_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-path-inside_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-redirect_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-retry-allowed_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-stream_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_is-typedarray_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_isexe_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_isstream_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsbn_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-parse-better-errors_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-schema-traverse_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_json-stringify-safe_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsonparse_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_jsprim_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_latest-version_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lazy-property_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lcid_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_libcipm_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpmhook_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpmhook_node_modules_npm-registry-fetch_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_libnpx_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_locate-path_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lock-verify_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lockfile_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._baseindexof_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._baseuniq_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._bindcallback_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._cacheindexof_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._createcache_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._createset_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._getnative_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash._root_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.clonedeep_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.restparam_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.union_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.uniq_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lodash.without_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lowercase-keys_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_lru-cache_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_make-dir_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_make-fetch-happen_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_meant_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mem_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mime-db_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mime-types_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mimic-fn_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_minimatch_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_minimist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_minipass_node_modules_yallist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_minizlib_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mississippi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mkdirp_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_move-concurrently_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ms_license.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_mute-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-fetch-npm_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_gyp_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_nopt_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_semver_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_node-gyp_node_modules_tar_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_nopt_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_normalize-package-data_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-audit-report_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-bundled_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-cache-filename_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-install-checks_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-lifecycle_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-logical-tree_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-package-arg_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-packlist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-pick-manifest_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-profile_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_node_modules_retry_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-client_node_modules_ssri_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_cacache_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_cacache_node_modules_mississippi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_figgy-pudding_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_make-fetch-happen_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_pump_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_smart-buffer_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_socks_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-registry-fetch_node_modules_ssri_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-run-path_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npm-user-validate_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_npmlog_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_number-is-nan_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_oauth-sign_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_object-assign_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_once_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_opener_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-homedir_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-locale_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_os-tmpdir_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_osenv_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-finally_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-limit_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-locate_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_p-try_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_package-json_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pacote_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_parallel-transform_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-exists_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-is-absolute_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-is-inside_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_path-key_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_performance-now_license.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pify_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_prepend-http_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_process-nextick-args_license.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-inflight_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-retry_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_promise-retry_node_modules_retry_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_promzard_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_proto-list_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_protoduck_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_prr_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pseudomap_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pump_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pumpify_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_pumpify_node_modules_pump_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_punycode_LICENSE-MIT.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_qrcode-terminal_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_qs_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_query-string_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_qw_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.APACHE2
/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.BSD
/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_LICENSE.MIT
/usr/share/package-licenses/nodejs/deps_npm_node_modules_rc_node_modules_minimist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-installed_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-package-json_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_read-package-tree_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_read_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_readable-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_readdir-scoped-modules_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_registry-auth-token_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_registry-url_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_request_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_require-directory_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_require-main-filename_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_resolve-from_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_retry_License
/usr/share/package-licenses/nodejs/deps_npm_node_modules_rimraf_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_safe-buffer_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_safer-buffer_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_semver-diff_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_semver_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_set-blocking_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sha_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_shebang-command_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_shebang-regex_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_signal-exit_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_slide_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_smart-buffer_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_socks_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-object_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_from2_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_readable-stream_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sorted-union-stream_node_modules_string_decoder_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_spdx-correct_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_spdx-expression-parse_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_sshpk_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_ssri_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-each_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-iterate_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_stream-shift_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_strict-uri-encode_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_ansi-regex_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_is-fullwidth-code-point_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_string-width_node_modules_strip-ansi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_string_decoder_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-ansi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-eof_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_strip-json-comments_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_supports-color_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tar_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tar_node_modules_yallist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_term-size_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_text-table_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_through2_LICENSE.html
/usr/share/package-licenses/nodejs/deps_npm_node_modules_through2_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_through_LICENSE.APACHE2
/usr/share/package-licenses/nodejs/deps_npm_node_modules_through_LICENSE.MIT
/usr/share/package-licenses/nodejs/deps_npm_node_modules_timed-out_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tiny-relative-date_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tough-cookie_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tunnel-agent_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_tweetnacl_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_typedarray_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_uid-number_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_umask_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_unique-string_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_unpipe_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_unzip-response_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_update-notifier_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_url-parse-lax_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_util-deprecate_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_util-extend_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_uuid_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_validate-npm-package-license_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_validate-npm-package-name_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_verror_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wcwidth_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_which-module_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_which_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wide-align_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wide-align_node_modules_string-width_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_widest-line_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_worker-farm_LICENSE.md
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrap-ansi_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrap-ansi_node_modules_string-width_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_wrappy_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_write-file-atomic_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_xdg-basedir_license
/usr/share/package-licenses/nodejs/deps_npm_node_modules_xtend_LICENCE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_y18n_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_yallist_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs-parser_LICENSE.txt
/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs_LICENSE
/usr/share/package-licenses/nodejs/deps_npm_node_modules_yargs_node_modules_y18n_LICENSE
/usr/share/package-licenses/nodejs/deps_openssl_openssl_LICENSE
/usr/share/package-licenses/nodejs/deps_openssl_openssl_crypto_bf_COPYRIGHT
/usr/share/package-licenses/nodejs/deps_openssl_openssl_crypto_des_COPYRIGHT
/usr/share/package-licenses/nodejs/deps_uv_LICENSE
/usr/share/package-licenses/nodejs/deps_uv_LICENSE-docs
/usr/share/package-licenses/nodejs/deps_v8_LICENSE
/usr/share/package-licenses/nodejs/deps_v8_LICENSE.fdlibm
/usr/share/package-licenses/nodejs/deps_v8_LICENSE.strongtalk
/usr/share/package-licenses/nodejs/deps_v8_LICENSE.v8
/usr/share/package-licenses/nodejs/deps_v8_LICENSE.valgrind
/usr/share/package-licenses/nodejs/deps_v8_src_third_party_valgrind_LICENSE
/usr/share/package-licenses/nodejs/deps_v8_src_third_party_vtune_LICENSE
/usr/share/package-licenses/nodejs/deps_v8_third_party_inspector_protocol_LICENSE
/usr/share/package-licenses/nodejs/deps_v8_third_party_jinja2_LICENSE
/usr/share/package-licenses/nodejs/deps_v8_third_party_markupsafe_LICENSE
/usr/share/package-licenses/nodejs/tools_doc_LICENSE
/usr/share/package-licenses/nodejs/tools_doc_node_modules_marked_LICENSE
/usr/share/package-licenses/nodejs/tools_gyp_LICENSE
